# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
before_script:
  - ./docker/travis
cache: packages
env:
  - VALIDATE_JSON_SCHEMAS=true
r_packages:
  - covr
r_github_packages:
  - mrc-ide/specio
  - ropensci/jsonvalidate@i20
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
