# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
addons:
  apt:
    packages:
      - libgdal-dev
      - libhiredis-dev
      - libjq-dev
      - libprotobuf-dev
      - libudunits2-dev
      - libv8-dev
      - protobuf-compiler
      - redis-server
services:
  - redis-server
before_script:
  - ./scripts/build_test_data
  - R CMD INSTALL .
  - Rscript -e 'install.packages(c("devtools", "roxygen2"))'
  - Rscript -e 'devtools::test()'
cache: packages
env:
  - VALIDATE_JSON_SCHEMAS=true USE_MOCK_MODEL=true
r_packages:
  - covr
r_github_packages:
  - ropensci/jsonvalidate
  - mrc-ide/eppasm
  - mrc-ide/naomi
  - mrc-ide/rrq@mrc-734
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
