# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
addons:
  apt:
    packages:
      - libgdal-dev
      - libhiredis-dev
      - libjq-dev
      - libprotobuf-dev
      - libudunits2-dev
      - libv8-dev
      - protobuf-compiler
      - redis-server
services:
  - redis-server
before_script:
  - R CMD INSTALL .
cache: packages
env:
  - VALIDATE_JSON_SCHEMAS=true
r_packages:
  - covr
r_github_packages:
  - ropensci/jsonvalidate@i25
  - mrc-ide/naomi
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
