# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - covr
r_github_packages:
  - mrc-ide/specio
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
