# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
addons:
  apt:
    packages:
      - libhiredis-dev
      - redis-server
      - libv8-dev
      - libjq-dev
      - libudunits2-dev
      - libprotobuf-dev
      - protobuf-compiler
before_script:
  - ./docker/travis
  - ./docker/build_test_containers
cache: packages
env:
  - VALIDATE_JSON_SCHEMAS=true
r_packages:
  - covr
r_github_packages:
  - ropensci/jsonvalidate@i25
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
