steps:
  - label: ":whale: Build"
    command: docker/build

  - wait

  - label: ":hammer: Unit tests"
    command: docker/test_check

  - label: ":hammer_and_pick: Integration tests"
    command: docker/test_integration

  - label: ":docker: Docker connection test"
    command: docker/test_connection

  - wait

  - label: ":shipit: Push images"
    command: docker/push

  - label: ":codecov: Codecov"
    command: docker/coverage
