steps:
  - label: ":whale: Build"
    command: docker/build

  - wait

  - label: ":hammer: Unit tests"
    command: docker/test_check
    key: "unit-tests"
    agents:
      queue: "parallel"

  - label: ":hammer_and_pick: Integration tests"
    command: docker/test_integration
    key: "integration-tests"

  - label: ":docker: Docker connection test"
    command: docker/test_connection
    key: "connection-tests"

  - label: ":codecov: Codecov"
    command: docker/coverage
    agents:
      queue: "parallel"

  - label: ":shipit: Push images"
    command: docker/push
    depends_on:
      - "unit-tests"
      - "integration-tests"
      - "connection-tests"

  - wait

  # This makes sure that deploys are triggered in the same order as the
  # test builds, no matter which test builds finish first.
  - label: "Concurrency gate"
    command: "exit 0"
    if: build.branch == 'master'
    concurrency: 1
    concurrency_group: "hint-deploy-concurrency-gate"

  - wait

  - label: ":rocket:"
    trigger: "naomi-staging-deploy"
    if: build.branch == 'master'
    build:
      message: "Triggered build"
