steps:
  - label: ":whale: Build"
    command: docker/build

  - wait

  - label: ":hammer: Unit tests"
    command: docker/test_check

  - wait

  - label: ":shipit: Push images"
    command: docker/push
