#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common

cat << EOF > $HERE/Dockerfile.worker
FROM $TAG_SHA
ENTRYPOINT ["/usr/local/bin/hintr_worker"]
EOF

cat << EOF > $HERE/Dockerfile.test
FROM $TAG_SHA
RUN install_packages --repo=https://mrc-ide.github.io/drat \
        devtools \
        mockery \
        covr \
        ssh
RUN install_remote \
        ropensci/jsonvalidate
WORKDIR /src
RUN R CMD build .
ENTRYPOINT ["R"]
EOF

rm -rf naomi

git clone --single-branch --branch mrc-1437 https://github.com/mrc-ide/naomi

docker build --pull \
       -t $TAG_SHA \
       -t $TAG_BRANCH \
       -t $TAG_VERSION \
       -f docker/Dockerfile \
       .

docker build \
       -t $TAG_WORKER_SHA \
       -t $TAG_WORKER_BRANCH \
       -t $TAG_WORKER_VERSION \
       -f docker/Dockerfile.worker \
       .

docker build \
      -t hintr_tests:${GIT_SHA} \
      -f docker/Dockerfile.test \
      .

rm -f docker/Dockerfile.worker
rm -f docker/Dockerfile.test

# We always push the SHA tagged versions, for debugging if the tests
# after this step fail
docker push $TAG_SHA
docker push $TAG_WORKER_SHA
