#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common

NAME_SERVER=hintr_server
NAME_NETWORK=hintr_network
NAME_VOLUME=hintr_volume

docker network create $NAME_NETWORK
docker volume create $NAME_VOLUME

docker run --rm -d --network=$NAME_NETWORK --network-alias=redis \
       --name hintr_redis redis
docker run --rm -d --network=$NAME_NETWORK \
       -p 8888:8888 \
       -e REDIS_URL=redis://redis:6379 \
       -e USE_MOCK_MODEL=true \
       --mount type=volume,src=$NAME_VOLUME,dst=/uploads \
       --name $NAME_SERVER $TAG_SHA

set +e
for attempt in $(seq 10); do
    echo "Attempt $attempt"
    RESPONSE=$(curl --silent http://localhost:8888)
    if [ "$RESPONSE" == '"Welcome to hintr"' ]; then
        echo "SUCCESS"
        exit 0
    fi
    sleep 0.5
done
