#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

# In case we switch agents between steps or tag has been updated
docker pull $TAG_SHA

NAME_REDIS=hintr_redis
NAME_NETWORK=hintr_network

function cleanup {
    echo "Cleaning up"
    docker kill $NAME_REDIS > /dev/null || true
    docker kill $NAME_HINTR_TESTS > /dev/null || true
    docker network rm $NAME_NETWORK > /dev/null || true
}

trap cleanup EXIT

docker network create $NAME_NETWORK

docker run --rm -d --network=$NAME_NETWORK --network-alias=redis \
       --name $NAME_REDIS redis

docker run --rm -it --network=$NAME_NETWORK \
       -e REDIS_URL=redis://redis:6379 \
       -e VALIDATE_JSON_SCHEMAS=true \
       -e PORCELAIN_VALIDATE=true \
       -e USE_MOCK_MODEL=true \
       -e _R_CHECK_CRAN_INCOMING_=FALSE \
       -e TESTTHAT_CPUS=$NUM_CORES \
       --entrypoint sh \
       --name $NAME_HINTR_TESTS \
       $TAG_HINTR_TESTS \
       -c "test_self"
