#!/usr/bin/env Rscript
setup <- function() {
  docker <- stevedore::docker_client()
  nw <- docker$network$create("hintr_nw")
  redis <- docker$container$run("redis", name = "redis",
                                network = nw, detach = TRUE, rm = TRUE)
  hintr <- docker$container$run("mrcide/hintr:master", name = "hintr",
                                ports = "8888:8888",
                                env = c(REDIS_URL = "redis://redis:6379",
                                        USE_MOCK_MODEL = "true"),
                                network = nw, detach = TRUE, rm = TRUE)

  url <- "http://localhost:8888"
  for (i in seq_len(5)) {
    message("Attempt ", i)
    ok <- tryCatch({
      httr::stop_for_status(httr::GET(url))
      TRUE
    }, error = function(e) FALSE)
    if (ok) {
      break
    }
    Sys.sleep(1)
  }
  if (!ok) {
    stop("Failed to bring up server in time")
  }

  function() {
    hintr$kill()
    redis$kill()
    nw$remove()
  }
}

run_command <- function(x, env) {
  cmd <- paste("curl -s", glue::glue(x$command, .envir = env))
  x$output <- system(cmd, intern = TRUE)
  if (x$format == "json") {
    parsed <- jsonlite::fromJSON(x$output)
  } else {
    parsed <- x$output
  }
  if (!is.null(x$collect)) {
    for (i in seq_along(x$collect)) {
      env[[names(x$collect)[[i]]]] <- parsed$data[[x$collect[[i]]]]
    }
  }
  if (!is.null(x$sleep)) {
    message("...waiting")
    Sys.sleep(x$sleep)
  }

  x
}

pretty_truncate <- function(x, format = "json", max = 20) {
  if (format == "json") {
    str <- strsplit(jsonlite::prettify(x), "\n", fixed = TRUE)[[1]]
  } else if (format == "bytes") {
    str <- sprintf("Hidden %d bytes of output", length(x))
  } else if (format == "header") {
    str <- paste(x, collapse = "\n")
  } else {
    stop(sprintf("Unknown format type %s", format))
  }

  if (length(str) > max) {
    str <- c(str[seq_len(max)],
             sprintf("... truncated %d lines of output", length(str) - max))
  }

  str
}

pretty_command <- function(x, width = 55) {
  x <- paste("$ curl", x)
  if (nchar(x) > width) {
    x <- strwrap(x, exdent = 4, width = width)
    i <- seq_len(length(x) - 1)
    x[i] <- paste(x[i], "\\")
  }
  x
}

render <- function(x) {
  c(x$comment,
    "",
    "```",
    pretty_command(x$command),
    "```",
    "",
    "```json",
    pretty_truncate(x$output, x$format),
    "```")
}

process <- function() {
  env <- new.env()
  dat <- yaml::read_yaml("README.yml")
  for (i in seq_along(dat)) {
    message(sprintf("%2d: %s", i, dat[[i]]$command))
    if (is.null(dat[[i]]$format)) {
      dat[[i]]$format <- "json"
    }
    dat[[i]] <- run_command(dat[[i]], env)
  }
  res <- lapply(dat, render)

  txt <- readLines("README.md.in")
  i <- which(txt == "HINT_EXAMPLES")
  stopifnot(length(i) == 1L)

  header <- "<!-- DO NOT EDIT - EDIT README.md.in INSTEAD! -->"
  readme <- c(header, txt[seq_len(i - 1)], unlist(res), txt[-seq_len(i)])
  writeLines(readme, "README.md")
}

main <- function() {
  cleanup <- setup()
  on.exit(cleanup())
  process()
}

if (!interactive()) {
  main()
}
