#!/usr/bin/env bash
set -eux

# This is specific to our main instances of hintr, and not part of the
# deploy tool, at least for now (hopefully won't be needed for
# long). We should download this script onto the incoming user with:
#
# curl -LO https://raw.githubusercontent.com/mrc-ide/hintr/mrc-1173/scripts/hintr_prerun_import
# chmod +x hintr_prerun_import
CONTAINER=hint_hintr
DEST=/prerun/incoming
PRERUN=/prerun

if [ $# -lt 1 ]; then
    echo "Usage:"
    echo "  $(basename $0) <source> ..."
    exit 1
fi

SRC=$1
shift

if [ ! -d $SRC ]; then
    echo "Expected first argument to be a directory"
    exit 1
fi

docker exec $CONTAINER rm -rf "$DEST"
docker cp $SRC $CONTAINER:$DEST
docker exec $CONTAINER hintr_prerun_import "/prerun" $DEST $@

function cleanup {
    docker exec $CONTAINER rm -rf "$DEST"
}
trap cleanup EXIT
