@description('The location where the resources will be created.')
param location string = 'eastus2'

@description('Name of the migration container.')
var migrateContainerName string = 'migrate-naomi'

@description('The name of the container apps environment. If set, it overrides the name generated by the template.')
param migrateImage string = 'ghcr.io/hivtools/migrate-naomi:latest'

@description('Name of the existing storage account')
param storageAccountName string = 'migratelogstorageaccount'

@description('Name for the migration file share')
param shareName string = 'migration-share'

@description('Name for the migration logs volume')
param volumeName string = 'migration-logs'

@description('Location to mount the file share')
param volumeMountPath string = '/migrations'

resource storageAccount 'Microsoft.Storage/storageAccounts@2026-04-01' = {
  name: storageAccountName
  location: location
  sku: {
    name: 'Standard_LRS'
  }
  kind: 'StorageV2'
}

// get storage account keys (for mounting)
var storageKey = storageAccount.listKeys().keys[0].value

@description('Create configured file shares')
resource fileShare 'Microsoft.Storage/storageAccounts/fileServices/shares@2023-05-01' = {
  name: '${storageAccount.name}/default/${shareName}'
}

@description('Name of the Naomi main storage account')
param naomiStorageAccountName string

@description('Name of the naomi results share')
param naomiStorageShareName string

resource naomiStorageAccount 'Microsoft.Storage/storageAccounts@2026-04-01' existing = {
  name: naomiStorageAccountName
}

// get storage account keys (for mounting)
var naomiStorageKey = naomiStorageAccount.listKeys().keys[0].value

@description('Create configured file shares')
resource naomiResultsShare 'Microsoft.Storage/storageAccounts/fileServices/shares@2023-05-01' existing = {
  name: '${naomiStorageAccountName}/default/${naomiStorageShareName}'
}

@description('Name of the redis service')
param redisName string

@description('Name of the redis database')
param redisDbName string

@description('Name of redis private DNS zone')
param redisPrivateDnsZoneName string

resource redis 'Microsoft.Cache/redisEnterprise@2025-08-01-preview' existing = {
  name: redisName
}

resource redisDb 'Microsoft.Cache/redisEnterprise/databases@2025-08-01-preview' existing = {
  name: redisDbName
  parent: redis
}

var redisConnectionString = 'redis://:${redisDb.listKeys().primaryKey}@${redisName}.${redisPrivateDnsZoneName}:10000'

@description('Name for the existing vnet')
param vnetName string

resource vnet 'Microsoft.Network/virtualNetworks@2024-01-01' existing = {
  name: vnetName
}

resource dbMigrateSubnet 'Microsoft.Network/virtualNetworks/subnets@2023-11-01' existing = {
  name: 'nm-hint-db-migrate-subnet'
  parent: vnet
}

resource naomiMigration 'Microsoft.ContainerInstance/containerGroups@2023-05-01' = {
  name: migrateContainerName
  location: location
  properties: {
    containers: [
      {
        name: migrateContainerName
        properties: {
          image: migrateImage
          command: [
            '/usr/local/bin/run_migration_2.10.21'
          ]
          environmentVariables: [
            {
              name: 'REDIS_URL'
              value: redisConnectionString
            }
          ]
          resources: {
            requests: {
              cpu: json('2')
              memoryInGB: json('4.0')
            }
          }
          volumeMounts: [
            {
              name: volumeName
              mountPath: volumeMountPath
              readOnly: false
            }
            {
              name: 'results-share'
              mountPath: '/results'
              readOnly: false
            }
          ]
        }
      }
    ]
    subnetIds: [
      {
        id: dbMigrateSubnet.id
        name: 'nm-hint-db-migrate-subnet'
      }
    ]
    osType: 'Linux'
    restartPolicy: 'Never'
    volumes: [
      {
        name: volumeName
        azureFile: {
          shareName: shareName
          storageAccountName: storageAccountName
          storageAccountKey: storageKey
        }
      }
      {
        name: 'results-share'
        azureFile: {
          shareName: naomiStorageShareName
          storageAccountName: naomiStorageAccountName
          storageAccountKey: naomiStorageKey
        }
      }
    ]
  }
}
