#!/usr/bin/env Rscript

## testthat imports pkgload so we can assume that's present here

testthat::test_file("tests/testthat/integration-server.R",
                    env = pkgload::load_all(".")$env)
