name: Build Docker Image

on:
  push:
    branches: [main, master, tmp-epic-plot-cleanup-input]
  pull_request:
    branches: [main, master, tmp-epic-plot-cleanup-input]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: extract_branch
        name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone Naomi
        uses: actions/checkout@v4
        with:
          repository: mrc-ide/naomi
          ## ${{ github.token }} is scoped to the current repository, so we
          ## need to provide our own PAT
          token: ${{ secrets.NAOMI_GH_PAT }}
          path: naomi

      - name: Build and push dev containers
        uses: docker/build-push-action@v5
        if: github.event_name == 'pull_request'
        with:
          context: .
          file: "./docker/Dockerfile"
          push: true
          tags: |
            mrcide/hintr:${{steps.extract_branch.outputs.branch}}
            ghcr.io/${{github.repository}}:${{steps.extract_branch.outputs.branch}}

      - name: Build and push prod containers
        uses: docker/build-push-action@v5
        if: github.event_name != 'pull_request'
        with:
          context: .
          file: "./docker/Dockerfile"
          push: true
          tags: |
            mrcide/hintr:latest
            mrcide/hintr:${{steps.extract_branch.outputs.branch}}
            ghcr.io/${{github.repository}}:latest
            ghcr.io/${{github.repository}}:${{steps.extract_branch.outputs.branch}}
