# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Integration test

jobs:
  integration:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    # Shorter timeout to prevent mac builders hanging for 6 hours!
    timeout-minutes: 90

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - name: Install libssh
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssh-dev

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: "https://duckdb.r-universe.dev https://mrc-ide.r-universe.dev"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools

      - name: Start Redis
        if: runner.os != 'Windows'
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "5.x"

      - name: Start Redis (windows)
        if: runner.os == 'Windows'
        run: |
          choco install memurai-developer
      - name: Build test data
        run: |
          ./scripts/build_test_data

      - name: Install hintr
        run: |
          Rscript -e 'devtools::install()'

      - name: Run integration tests
        run: |
          ./scripts/test_integration
